[package]
name = "bobs8085"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = [ "debug" ] }
tokio = "1.47.1"

# CLI Binary
[[bin]]
name = "bobs8085"
path = "src/main.rs"


# CLI Binary
[[bin]]
name = "bobs8085-gui"
path = "src/gui.rs"
