name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            asset_name_suffix: "linux-x86_64.tar.gz"
            binary_name: "bobs8085"

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            asset_name_suffix: "windows-x86_64.zip"
            binary_name: "bobs8085.exe"

          - os: macos-latest
            target: x86_64-apple-darwin
            asset_name_suffix: "macos-x86_64.tar.gz"
            binary_name: "bobs8085"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package for release
        shell: bash
        run: |
          mkdir staging
          
          if [ "${{ runner.os }}" == "Windows" ]; then
            cp "target/${{ matrix.target }}/release/${{ matrix.binary_name }}" "staging/"
            cd staging
            7z a "../release-asset.zip" *
          else
            cp "target/${{ matrix.target }}/release/${{ matrix.binary_name }}" "staging/"
            cd staging
            tar czf "../release-asset.tar.gz" *
          fi
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-asset-${{ matrix.target }}
          path: release-asset.*

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build 
    
    permissions:
      contents: write 

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts 

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: artifacts/**/*
