name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest # The main job runner, it will orchestrate everything

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build binaries for all platforms
        uses: tauri-apps/cross-platform-build@v2
        with:
          targets: 'x86_64-unknown-linux-gnu, x86_64-apple-darwin, x86_64-pc-windows-msvc'
          projectPath: '.'
          binaryName: 'bobs8085'

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            bobs8085*
