name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cli_binary_name: "bobs8085"
            gui_binary_name: "bobs8085-gui"
            osname: "linux"

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            cli_binary_name: "bobs8085.exe"
            gui_binary_name: "bobs8085-gui.exe"
            osname: "windows"

          - os: macos-latest
            target: x86_64-apple-darwin
            cli_binary_name: "bobs8085"
            gui_binary_name: "bobs8085-gui"
            osname: "macos"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build binaries
        run: |
          cargo build --bin bobs8085 --release --target ${{ matrix.target }}
          cargo build --bin bobs8085-gui --release --target ${{ matrix.target }}

      - name: Package for release
        shell: bash
        run: |
          mkdir staging

          cp "target/${{ matrix.target }}/release/${{ matrix.cli_binary_name }}" "staging/"
          cp "target/${{ matrix.target }}/release/${{ matrix.gui_binary_name }}" "staging/"

          if [ "${{ runner.os }}" == "Windows" ]; then
            cd staging
            7z a "../bobs8085-${{ matrix.osname }}.zip" *
          else
            cd staging
            tar czf "../bobs8085-${{ matrix.osname }}.tar.gz" *
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bobs8085-${{ matrix.target }}-${{ matrix.osname }}
          path: bobs8085-*.zip # More specific path for zip
          if-no-files-found: ignore
      - name: Upload artifact (tar.gz)
        uses: actions/upload-artifact@v4
        with:
          name: bobs8085-${{ matrix.target }}-${{ matrix.osname }}
          path: bobs8085-*.tar.gz # More specific path for tar.gz
          if-no-files-found: ignore


  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: artifacts/**/*
